### ISSUE TITLE
Publish on Open-VSX?

### ISSUE THREAD

**Issue by yashpalgoyal1304** [wraith13/bracket-lens-vscode#15]
Hi!
Congratulations of getting ur extension [published]. I just thought to ask that do u have any plans to publish ur extension on open-vsx??
See this for more details: [wraith13.bracket-lens]
Thanks!

[published]: https://code.visualstudio.com/updates/v1_62#_web-extensions
[wraith13.bracket-lens]: https://open-vsx.org/vscode/item?itemName=wraith13.bracket-lens

**Comment by wraith13** [comment]
When I found out about open-vsx, I thought about publishing my VS Code extensions to open-vsx.
However, I laughed and was discouraged because the repository of tools for uploading to open-vsx, which claims to be open source, was private.

open-vsx which is not completely open source, is inconsistent with its reason for existence.

**Comment by yashpalgoyal1304** [comment]
> the repository of tools for uploading to open-vsx, which claims to be open source, was private

hmm, that's interesting, i'd like to know about it. can u share more details on it?

**Comment by wraith13** [comment]
VS Code: https://www.npmjs.com/package/vsce
![image](https://user-images.githubusercontent.com/645907/141652886-dd67f978-a0ce-4017-a35f-bb7fa5ad1157.png)

open-vsx: https://www.npmjs.com/package/ovsx
![image](https://user-images.githubusercontent.com/645907/141652897-f0d76130-72ed-4dca-b6e7-632b700aa769.png)

**Comment by yashpalgoyal1304** [comment]
> pen-vsx: https://www.npmjs.com/package/ovsx

did u intend to search for this repo: https://github.com/eclipse/openvsx ??

**Comment by yashpalgoyal1304** [comment]
P.S. nice texture on annotation, which software u used for annotating?? 🤔
