### ISSUE TITLE
Error msg at the head of every JSON file

### ISSUE THREAD

**Issue by benjamin-rood** [wraith13/bracket-lens-vscode#19]
Issue Type: <b>Bug</b>

![image](https://user-images.githubusercontent.com/10102132/153418295-e1c913bb-4f4b-471d-9bf3-56df4e0fa1c4.png)

Next to the opening`{` token of any JSON file shows an error: 
```
'definitions/colorGroup' in 'vscode://schemas/textmate-colors' can not be resolved.`
```

Used Extension Bisect to identify that it only occurs with Bracket Lens enabled.

Extension version: 1.5.1
VS Code version: Code 1.64.1 (d6ee99e4c045a6716e5c653d7da8e9ae6f5a8b03, 2022-02-07T17:17:47.733Z)
OS version: Linux x64 5.15.15-76051515-generic snap
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 9 5900X 12-Core Processor (24 x 2800)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|62.79GB (49.28GB free)|
|Process Argv|--no-sandbox . --crash-reporter-id c285745a-f157-4314-a1ff-b56ee5cf4da7|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|pop|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|pop|
|XDG_SESSION_TYPE|x11|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
pythonvspyl392:30425749
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30433059
pythonvs932:30410667
wslgetstartedc:30433508
vs360cf:30404996
vsrem710:30416614

```

</details>

**Comment by Detnator-Neo** [comment]
I'm experiencing this too.  Opening `{` or `[` of any JSON file (first noticed in settings.json).  Only when Bracket Lets is enabled.

Don't know if this is relevant or will help, bit I figured it out doing a search on my Mac for pieces of the error string.  Found at least one line in: `~/.vscode/extensions/wraith13.bracket-lens-1.5.1/package.json`. 
Line 85: `"contributes"."configuration"."properties"."bracketLens.color"."$ref" : "vscode://schemas/textmate-colors#definitions/colorGroup"`


Extension version: 1.5.1
VS Code version: Code 1.64.2 (f80445acd5a3dadef24aa209168452a3d97cc326, 2022-02-09T22:00:58.347Z)
OS version: macOS 12.2.1 (Darwin arm64 21.3.0)
2021 14" MacBook Pro, M1 Max CPU, 64GB RAM.

**Comment by nuunoo1977** [comment]
Same problem with me

**Comment by darklore** [comment]
Same with me too

**Comment by diegoazh** [comment]
Same here

**Comment by danielcastilho** [comment]
same error, i had to disable this extension...

**Comment by diegoazh** [comment]
me too @danielcastilho

**Comment by benjamin-rood** [comment]
Fixed with [release](https://github.com/wraith13/bracket-lens-vscode/blob/master/CHANGELOG.md#152---2022-07-02) last year, just retested on my massive settings.json, working fine, thanks @MarximusMaximus!
