### ISSUE TITLE
disable for certain languages option

### ISSUE THREAD

**Issue by ctf0** [wraith13/bracket-lens-vscode#2]
many thanx for this, it does make a big difference.

i was wondering if its possible to disable on certain languages ex.`php, css, etc...` ?

**Comment by wraith13** [comment]
The settings for this extension is "language-overridable" except for "bracketLess.debug".
You can make language-specific settings as shown below in `settings.json`.

```json
            "[php]":
            {
                "bracketLens.enabled": false
            },
            "[css]":
            {
                "bracketLens.prefix": " // "
            }
```

**Comment by ctf0** [comment]
disabling it for `php` sadly didnt work, it may have some interference with https://marketplace.visualstudio.com/items?itemName=CodeBiscuits.css-biscuits

**Comment by wraith13** [comment]
When I tried it in my environment, it stopped working properly in php with this specification.

```json
"[php]":
{
    "bracketLens.enabled": false
}
```

There seems to be a communication discrepancy, so please attach a screenshot of the settings and PHP code.

**Comment by ctf0** [comment]
> so please attach a screenshot of the settings and PHP code.

![demo](https://user-images.githubusercontent.com/7388088/96904100-f26fdf80-1496-11eb-92ef-cf2b8c1e64fe.gif)

**Comment by wraith13** [comment]
It seems to be quite different from the VS Code I know, please tell me the version and OS of VS Code.

Also, does this problem reappear if you disable all the other extensions?

**Comment by ctf0** [comment]
> please tell me the version and OS of VS Code

```
Version: 1.51.0-insider
Commit: 9f7a586124ca121bba906b44eb8356691617957e
Date: 2020-10-22T00:46:08.325Z
Electron: 9.3.2
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 18.7.0
```

> does this problem reappear if you disable all the other extensions?

its mostly related to using another ext that also add lens info like https://marketplace.visualstudio.com/items?itemName=CodeBiscuits.css-biscuits

**Comment by wraith13** [comment]
It's too different from VS Code in my environment, which is similar to the one you taught me. Is it genuine VS Code? The variant VS Code cannot be supported.

It also cannot support issues in combination with other minor extensions, apart from major extensions.

**Comment by ctf0** [comment]
> is it genuine VS Code?

if u mean the tabs & styling, they are a personal mod.

> It also cannot support issues in combination with other minor extensions, apart from major extensions.

ok np, i think this might be an issue with vscode as it cant separate the code lens from one ext to another.

still thanx for the headsup.
