### ISSUE TITLE
Show scopes only when some keys have been pressed

### ISSUE THREAD

**Issue by settyan117** [wraith13/bracket-lens-vscode#3]
Thanks a lot for this wonderful extension!

I would like to see bracket scopes only when I'm pressing some keys (e.g. Ctrl+{key}). Showing scopes at all times increases information on the editor, then I think it can make the code hard to read.

Is there already exists some settings to do this?

**Comment by wraith13** [comment]
I initially thought about it, but stopped because the VS Code API didn't provide up/down key event. 

However, I would like to consider providing a command to toggle the display. If there is a command, it is possible to assign a shortcut key.

**Comment by wraith13** [comment]
オレ(I)、日本語(Japanese)、ワカル(understand)。オマエも(You, too)、日本語、ワカル。
オレ、日本語、書く(write)。

v1.2.0 で対応した(supported)。オレ、この issue 、close する。
v1.2.0 で問題があったら( If there are problems )、オマエ、この issue 、reopen しろ。

**Comment by settyan117** [comment]
ありがとうございます！
